### ISSUE TITLE
Change name to 'geoglyphs'

### ISSUE THREAD

**Issue by lyzidiamond** [cugos/geoglyphs#1]
I mean, if you want. It came to me after our discussion. I think it's cute.

**Comment by mapsam** [comment]
Much better!

**Comment by mapsam** [comment]
closed in 60e7ff49b80d8e20297303bbf550ed73fae28bf2

**Comment by lyzidiamond** [comment]
:+1: :grapes: :microphone:

**Comment by powersa** [comment]
hooo hoooo!
