### ISSUE TITLE
s/bezzier/bezier

### ISSUE THREAD

**Issue by ungoldman** [cugos/geoglyphs#5]
Noticed on the site that bezier is spelled "bezzier" -- is that intentional?

https://github.com/cugos/geoglyphs/blob/db998c942d128290d026e8017af59c94dda9ff02/icons.json#L17-L18

https://github.com/cugos/geoglyphs/blob/db998c942d128290d026e8017af59c94dda9ff02/src/turf-bezzier.svg#L5

**Comment by mapsam** [comment]
That is not intentional! Just my poor grammar :stuck_out_tongue_closed_eyes:

**Comment by ngoldman** [comment]
Hi! Reviewing old issues I opened to try to reduce my issue load. @mapsam wanna change to correct spelling or close since it doesn't really affect anything?

**Comment by mapsam** [comment]
bam.

**Comment by ngoldman** [comment]
Yay!
